### ISSUE TITLE
Debouncing

### ISSUE THREAD

**Issue by ilias-t** [mattjmattj/simple-undo#2]
Would be nice to debounce the keydown events so that an undo/redo would update the state with a chunk of data that is representative of a distinct time block.

**Comment by jonas-lauber** [comment]
This has absolutely nothing to do with the library... If you want a debouncer just put one... You're responsible to chose when history.save() is called...

**Comment by mattjmattj** [comment]
I agree with @jonas-lauber . I'll close this one.
Thank you for contributing :)
