### ISSUE TITLE
Help - Not working in the browser

### ISSUE THREAD

**Issue by noisiak** [mattjmattj/simple-undo#4]
Hello! I am using the library on a web page and I can't manage to make it work.
This is what I did:
1. Load simple-undo.js on my head tag.
2. Run the example script in the readme (I copied on my script.js, which I load after the simple-undo.js)
3. Got error: "history.save is not a function".

I am still learning JS so I am probably missing something basic. Hope someone could help me on this.

**Comment by mattjmattj** [comment]
Hi!
Does the demo page work for you ? http://mattjmattj.github.io/simple-undo/

**Comment by noisiak** [comment]
Yeah! Thanks, now it is working. I am not sure what was wrong before (I guess I was missing something). I just started from zero again and now its working.

**Comment by mattjmattj** [comment]
Nice. I'm closing the issue, then :)
